### PR TITLE
do not redefine a kernel spec with a lower precedence one

### PR DESCRIPTION
**Pull request by haraldschilly**
see issue #28

The only new thing is the "if", the other part is a mockup python3 kernel and a line to test it.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Excellent!

/cc @lgeiger -- we'll want to bring this into the monorepo merger too.

**Comment by rgbkrk** [comment]
I'm going to get the CI fixed up here.

**Comment by rgbkrk** [comment]
Thanks @haraldschilly!

**Comment by haraldschilly** [comment]
thank you for quickly reviewing it. will there be a new release with the fix?

**Comment by rgbkrk** [comment]
Yeah, I'm going to go ahead and get everything upgraded here as well as in other packages too: https://github.com/nteract/kernelspecs/pull/30

**Comment by rgbkrk** [comment]
Released `v2.0.0` (as well as all the packages that depend on it within nteract).

**Comment by rgbkrk** [comment]
Harald, what's your username on npm? I'd love to add you to the `@nteract` org as well as the individual packages for `kernelspecs` and related packages that sage math cloud is relying on.

**Comment by haraldschilly** [comment]
@rgbkrk ok, I'm not active there (at least so far), but anyways: "hasch"

**Comment by rgbkrk** [comment]
Tis ok, I'm not handing you immediate responsibility to take care of anything, just the ability later. 😄

**Pull request merged**
