### PR TITLE
Fix error if no kernelspecs can be found

### PR DESCRIPTION
**Pull request by lgeiger**
Prevents https://github.com/nteract/nteract/issues/988

### CODE REVIEW

**Comment by rgbkrk** [comment]
I feel like the responsibility is on us to catch it in nteract. If we squash the error we get no insight.

**Comment by lgeiger** [comment]
I don't think the error message is helpful:

```
TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at Promise.all.then.kernelInfos (/home/lukasgeiger/code/nteract/node_modules/kernelspecs/lib/traverse.js:64:8)
```

But I'm OK with leaving it.
This would mean we have to rewrite the usage in nteract since `kernelspecs.findAll()` is called three times ([1](https://github.com/nteract/nteract/blob/master/src/main/index.js#L58), [2](https://github.com/nteract/nteract/blob/master/src/main/index.js#L88), [3](https://github.com/nteract/nteract/blob/master/src/main/index.js#L128)) but we only catch the error one time.

**Comment by lgeiger** [comment]
I can't reproduce https://github.com/nteract/nteract/issues/988 on OS X. It only happens on my ubuntu machine.

**Comment by rgbkrk** [comment]
We could catch and then throw a more useful error message. Alternatively, we can do a bounds check where we need to before the reduce.

**Comment by lgeiger** [comment]
Oh I think I found a much better fix. Looks like it was too late for me to realize this yesterday.

**Review by rgbkrk — APPROVED** [review]

**Comment by lgeiger** [comment]
I think we should ship a patch release. (I could do it but I don't have npm access)

**Comment by rgbkrk** [comment]
K, I'm on my bike now. I can give you access soon.

**Pull request merged**
