### PR TITLE
Problem: code wasn't modular enough to test

### PR DESCRIPTION
**Pull request by rgbkrk**
Solution: Extract it

This also makes our exported interface on `require('kernelspecs')` be an Object instead of a function.

### CODE REVIEW

**Comment by jdfreder** [comment]
Oh cool, looks like exporting by name was a good idea

**Comment by rgbkrk** [comment]
Think we're fit to ship this as 1.0.0? Most excellent Promise work here.

**Comment by jdfreder** [comment]
I think so - want me to?

**Comment by rgbkrk** [comment]
Sure!

**Pull request merged**
